export const inputsArray = [
	{
		label: "Название",
		name: "name",
		type: "text",
		placeholder: "Введите название фильма",
		className: "input dialog__form--input",
		classNameLabel: "",
		required: true,
	},
	{
		label: "Год выпуска",
		name: "releaseYear",
		type: "number",
		placeholder: "Введите год выпуска фильма",
		className: "input dialog__form--input",
		classNameLabel: "",
		required: true,
	},
	{
		label: "Жанры",
		name: "genres",
		type: "text",
		placeholder: "Введите жанры фильма",
		className: "input dialog__form--input",
		classNameLabel: "",
		required: true,
	},
	{
		label: "Постер",
		name: "poster",
		type: "file",
		placeholder: "",
		className: "input dialog__form--input",
		classNameLabel: "",
	},
	{
		label: "Описание",
		name: "description",
		type: "text",
		placeholder: "Введите описание фильма",
		className: "input dialog__form--input",
		classNameLabel: "",
		required: true,
	},
];
